// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionService.Context;

#nullable disable

namespace SessionService.Migrations
{
    [DbContext(typeof(SessionServiceDbContext))]
    partial class SessionServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SessionService.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("SessionService.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("SessionService.Models.DungeonMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DMs");
                });

            modelBuilder.Entity("SessionService.Models.Joins.CampaignDungeonMaster", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("DungeonMasterId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "DungeonMasterId");

                    b.HasIndex("DungeonMasterId");

                    b.ToTable("CampaignDungeonMasters");
                });

            modelBuilder.Entity("SessionService.Models.Joins.CampaignPlayer", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CampaignPlayers");
                });

            modelBuilder.Entity("SessionService.Models.Joins.DmSession", b =>
                {
                    b.Property<int>("DungeonMasterId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("DungeonMasterId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("DmSessions");
                });

            modelBuilder.Entity("SessionService.Models.Joins.LocationOrganization", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("LocationOrganizations");
                });

            modelBuilder.Entity("SessionService.Models.Joins.LocationSession", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("LocationSessions");
                });

            modelBuilder.Entity("SessionService.Models.Joins.NpcOrganization", b =>
                {
                    b.Property<int>("NpcId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("NpcId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("NpcOrganizations");
                });

            modelBuilder.Entity("SessionService.Models.Joins.OrganizationSession", b =>
                {
                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("OrganizationId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("OrganizationSessions");
                });

            modelBuilder.Entity("SessionService.Models.Joins.PlayerSession", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("SessionService.Models.Joins.SessionNpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NpcId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NpcId");

                    b.HasIndex("SessionId", "NpcId")
                        .IsUnique();

                    b.ToTable("SessionNpcs");
                });

            modelBuilder.Entity("SessionService.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SessionService.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("SessionId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SessionService.Models.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("SessionService.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("SessionService.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SessionService.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SessionService.Models.Character", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", null)
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId");

                    b.HasOne("SessionService.Models.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SessionService.Models.Joins.CampaignDungeonMaster", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", "Campaign")
                        .WithMany("CampaignDungeonMasters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.DungeonMaster", "DungeonMaster")
                        .WithMany("CampaignDungeonMasters")
                        .HasForeignKey("DungeonMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("DungeonMaster");
                });

            modelBuilder.Entity("SessionService.Models.Joins.CampaignPlayer", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", "Campaign")
                        .WithMany("CampaignPlayers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Player", "Player")
                        .WithMany("CampaignPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SessionService.Models.Joins.DmSession", b =>
                {
                    b.HasOne("SessionService.Models.DungeonMaster", "DungeonMaster")
                        .WithMany("DmSessions")
                        .HasForeignKey("DungeonMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Session", "Session")
                        .WithMany("DmSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungeonMaster");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionService.Models.Joins.LocationOrganization", b =>
                {
                    b.HasOne("SessionService.Models.Location", "Location")
                        .WithMany("LocationOrganizations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Organization", "Organization")
                        .WithMany("LocationOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SessionService.Models.Joins.LocationSession", b =>
                {
                    b.HasOne("SessionService.Models.Location", "Location")
                        .WithMany("LocationSessions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Session", "Session")
                        .WithMany("LocationSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionService.Models.Joins.NpcOrganization", b =>
                {
                    b.HasOne("SessionService.Models.Npc", "Npc")
                        .WithMany("NpcOrganizations")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Organization", "Organization")
                        .WithMany("NpcOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SessionService.Models.Joins.OrganizationSession", b =>
                {
                    b.HasOne("SessionService.Models.Organization", "Organization")
                        .WithMany("OrganizationSessions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Session", "Session")
                        .WithMany("OrganizationSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionService.Models.Joins.PlayerSession", b =>
                {
                    b.HasOne("SessionService.Models.Player", "Player")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Session", "Session")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionService.Models.Joins.SessionNpc", b =>
                {
                    b.HasOne("SessionService.Models.Npc", "Npc")
                        .WithMany("SessionNpcs")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionService.Models.Session", "Session")
                        .WithMany("SessionNpcs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionService.Models.Location", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", null)
                        .WithMany("Locations")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("SessionService.Models.Note", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", "Campaign")
                        .WithMany("Notes")
                        .HasForeignKey("CampaignId");

                    b.HasOne("SessionService.Models.Session", "Session")
                        .WithMany("Notes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionService.Models.Npc", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", null)
                        .WithMany("Npcs")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("SessionService.Models.Organization", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", null)
                        .WithMany("Organizations")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("SessionService.Models.Session", b =>
                {
                    b.HasOne("SessionService.Models.Campaign", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("SessionService.Models.Campaign", b =>
                {
                    b.Navigation("CampaignDungeonMasters");

                    b.Navigation("CampaignPlayers");

                    b.Navigation("Characters");

                    b.Navigation("Locations");

                    b.Navigation("Notes");

                    b.Navigation("Npcs");

                    b.Navigation("Organizations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SessionService.Models.DungeonMaster", b =>
                {
                    b.Navigation("CampaignDungeonMasters");

                    b.Navigation("DmSessions");
                });

            modelBuilder.Entity("SessionService.Models.Location", b =>
                {
                    b.Navigation("LocationOrganizations");

                    b.Navigation("LocationSessions");
                });

            modelBuilder.Entity("SessionService.Models.Npc", b =>
                {
                    b.Navigation("NpcOrganizations");

                    b.Navigation("SessionNpcs");
                });

            modelBuilder.Entity("SessionService.Models.Organization", b =>
                {
                    b.Navigation("LocationOrganizations");

                    b.Navigation("NpcOrganizations");

                    b.Navigation("OrganizationSessions");
                });

            modelBuilder.Entity("SessionService.Models.Player", b =>
                {
                    b.Navigation("CampaignPlayers");

                    b.Navigation("Characters");

                    b.Navigation("PlayerSessions");
                });

            modelBuilder.Entity("SessionService.Models.Session", b =>
                {
                    b.Navigation("DmSessions");

                    b.Navigation("LocationSessions");

                    b.Navigation("Notes");

                    b.Navigation("OrganizationSessions");

                    b.Navigation("PlayerSessions");

                    b.Navigation("SessionNpcs");
                });
#pragma warning restore 612, 618
        }
    }
}
